version: '3'
x-compose:
  project: green-stack
services:
  server_green:
    container_name: demo_green
    image: demo
    depends_on:
      - rabbit_green
    environment:
      ENV: Green
      RABBITMQ_HOST: 172.22.0.6
      RABBITMQ_PORT: 5673
    expose:
      - 5000
    networks:
      broker_network:
        ipv4_address: 172.22.0.3
    volumes:
      - ./logs/app.log:/app/logs/app.log

  nginx:
    container_name: demo_nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/access.log:/var/log/nginx/access.log
      - ./nginx/log/error.log:/var/log/nginx/error.log
    networks:
      broker_network:
        ipv4_address: 172.22.0.4

  rabbit_green:
    container_name: demo_rabbit_green
    image: rabbitmq:management
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      broker_network:
        ipv4_address: 172.22.0.6

networks:
  broker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
